USE [BugLog]
GO
/****** Object:  Table [dbo].[ReportedBy]    Script Date: 09/02/2018 18:45:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReportedBy](
	[UserID] [int] NOT NULL,
	[BugID] [int] NOT NULL,
 CONSTRAINT [PK_ReportedBy] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[BugID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
