USE [master]
GO
/****** Object:  Database [BugLog]    Script Date: 09/02/2018 18:27:00 ******/
CREATE DATABASE [BugLog] ON  PRIMARY 
( NAME = N'BugLog', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.2\MSSQL\DATA\BugLog.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BugLog_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.2\MSSQL\DATA\BugLog_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'BugLog', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugLog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BugLog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BugLog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BugLog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BugLog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BugLog] SET ARITHABORT OFF 
GO
ALTER DATABASE [BugLog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BugLog] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BugLog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BugLog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BugLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BugLog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BugLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BugLog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BugLog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BugLog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BugLog] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BugLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BugLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BugLog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BugLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BugLog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BugLog] SET  READ_WRITE 
GO
ALTER DATABASE [BugLog] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BugLog] SET  MULTI_USER 
GO
ALTER DATABASE [BugLog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BugLog] SET DB_CHAINING OFF 